"""Company

Revision ID: 3562302028fa
Revises: a60a80bdf81f
Create Date: 2023-04-08 17:34:02.399634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3562302028fa'
down_revision = 'a60a80bdf81f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
