"""CompanyModerator

Revision ID: 70e9a2ae0c59
Revises: 3562302028fa
Create Date: 2023-04-08 17:36:40.946898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e9a2ae0c59'
down_revision = '3562302028fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_moderators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_user_id'], ['base_users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_moderators_id'), 'company_moderators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_moderators_id'), table_name='company_moderators')
    op.drop_table('company_moderators')
    # ### end Alembic commands ###
