"""Course

Revision ID: 951d6445c4f8
Revises: 70e9a2ae0c59
Create Date: 2023-04-08 18:03:01.888907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951d6445c4f8'
down_revision = '70e9a2ae0c59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
