"""user-task

Revision ID: e58b482698a5
Revises: e64ae32ab9e8
Create Date: 2023-04-09 12:47:52.791776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58b482698a5'
down_revision = 'e64ae32ab9e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_tasl_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tasks', ['current_tasl_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_tasl_id')
    # ### end Alembic commands ###
